name: Publish in Crate Package Registry

on:  
  push:
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Check formatting
      run: cargo fmt -- --check --verbose
    - name: Check style
      run: cargo clippy -- -D warnings
    - name: Publish crate
      run: cargo publish --token "$TOKEN"
      env:
        TOKEN: ${{ secrets.CRATES_API_TOKEN }}
